Feat: add validations map
fenol64/cube3d pull request #4
Opened 2024-06-08 18:39 UTC by AllanDantas21

- Tive que mudar a função de valid_colors: tava retornando true sempre, e ai zoava a validação.

- criei funções para mallocar o mapa todo apartir do map_index, depois ele passa no flood fill, 
   e checo se tem como o player ir para fora do mapa, criei uma struct pos para pegar a posição do player pro flood fill.

- depois vou criar uma função para copiar a matriz do mapa só pra validar, pq o flood fill tá alterando o mapa 
   da struct original da cube.

2024-06-08 20:08 UTC, fenol64 requested changes

2024-06-08 20:08 UTC, fenol64 commented on src/validations/validate_map.c
> +	get_map(path, &aux);
pq chama duas vezes?

2024-06-08 20:08 UTC, fenol64 commented on src/validations/validate_map.c
> +			if (map[i][j] == 'N' || map[i][j] == 'E' || map[i][j] == 'S' || map[i][j] == 'W')
seria legal colocar essa verificação numa função tipo: verify_player_position e as posições serem um enum

2024-06-08 20:08 UTC, fenol64 commented on src/validations/validate_map.c
> +	t_pos	player;
acha válido colocar isso na struct principal pra gente alterar essa pos dps? ou vai ser outra coisa?

2024-06-08 20:08 UTC, fenol64 commented on src/validations/validate_map.c
> +	printf("\n x: %d, y: %d\n", player.x, player.y);
printf nnnnnnnnnnnnnnnn

2024-06-08 20:36 UTC, AllanDantas21 commented on src/validations/validate_map.c
> +	printf("\n x: %d, y: %d\n", player.x, player.y);
esses foram de uns commits enquanto testava ksks

2024-06-08 20:36 UTC, AllanDantas21 commented on src/validations/validate_map.c
> +	get_map(path, &aux);
esses foram de uns commits enquanto testava ksks

2024-06-08 20:37 UTC, AllanDantas21 commented on src/validations/validate_map.c
> +	t_pos	player;
acho que é uma boa mesmo, não vai precisar chamar a função dnv dps

2024-06-08 21:23 UTC, AllanDantas21 commented on src/validations/validate_map.c
> +	t_pos	player;
adicionei essa struct de pos na t_cube

2024-06-10 00:56 UTC, fenol64 approved these changes

2024-06-10 00:56 UTC, merged